export const MECHANISMS = {
  'Phasic Stretch Reflex (Dynamic Myotatic Reflex / Tendon Jerks)': [
    'Stimulus: A sudden, rapid stretch of the muscle occurs (e.g., striking the patellar tendon with a reflex hammer).',
    'Receptor Activation: The muscle spindle, specifically the primary (annulospiral) endings in the nuclear bag fibers, is distorted by the stretch.',
    'Afferent Pathway: Sensory impulses are generated and conducted via large, fast Group Ia afferent fibers to the spinal cord.',
    'Center/Integration: The Ia fiber enters the dorsal root and branches in the anterior horn of the spinal cord.',
    'Monosynaptic Relay: One branch terminates directly on the alpha ($\\alpha$) motor neurons of the same (homonymous) muscle.',
    'Reciprocal Inhibition: Another branch terminates on an inhibitory interneuron (Golgi bottle neuron), which inhibits the $\\alpha$ motor neurons of the antagonist (heteronymous) muscle.',
    'Efferent Response: The stimulated $\\alpha$ motor neurons send impulses back to the muscle.',
    'Effector Action: The extrafusal skeletal muscle fibers contract powerfully, while the antagonist muscle relaxes.',
    'Response: A rapid, transient limb movement (e.g., the knee jerk) occurs to oppose the sudden change in length.',
  ],
  'Tonic Stretch Reflex (Static Myotatic Reflex)': [
    'Stimulus: A sustained or maintained stretch is applied to the muscle (often due to the pull of gravity).',
    'Receptor Activation: Both primary and secondary (flower-spray) endings of the muscle spindle (mainly in nuclear chain fibers) discharge continuously.',
    'Afferent Pathway: Information regarding the degree of maintained stretch is transmitted via Group Ia and Group II afferent fibers.',
    'Center: Like the phasic reflex, these fibers make direct monosynaptic connections with $\\alpha$ motor neurons in the spinal cord.',
    'Response: A continuous, weaker contraction persists as long as the stretch remains, maintaining muscle tone.',
  ],
  'Inverse Stretch Reflex (Golgi Tendon Reflex / Autogenic Inhibition)': [
    'Stimulus: A strong stretch or an intense active muscle contraction occurs.',
    'Receptor Activation: The Golgi Tendon Organ (GTO), arranged in series with muscle fibers, is stimulated by the high force/tension.',
    'Afferent Pathway: Impulses are transmitted via large Group Ib afferent fibers to the spinal cord.',
    'Center/Integration: Ib fibers terminate on inhibitory interneurons in the dorsal horn.',
    'Efferent Modulation: The inhibitory interneurons project to and inhibit the $\\alpha$ motor neurons supplying the same (agonist) muscle.',
    'Response: The agonist muscle instantaneously relaxes (autogenic inhibition), preventing potential injury like muscle tearing or tendon avulsion.',
  ],
  'Withdrawal Reflex (Flexor Reflex / Nociceptive Reflex)': [
    'Stimulus: Application of a noxious or painful stimulus (e.g., heat, pinprick).',
    'Receptor Activation: Nociceptors (pain receptors) in the skin, muscle, or joints are activated.',
    'Afferent Pathway: Impulses travel via flexor reflex afferents (FRA), consisting of small myelinated Group III (A$\\delta$) and unmyelinated Group IV (C) fibers.',
    'Center/Integration: Afferents enter the spinal cord and diverge to terminate on multiple pools of interneurons.',
    'Ipsilateral Flexion: One pathway excites $\\alpha$ motor neurons of the flexor muscles on the stimulated side.',
    'Ipsilateral Reciprocal Inhibition: Another pathway inhibits $\\alpha$ motor neurons of the extensor muscles on the stimulated side.',
    'Crossed Extensor Reflex: Commissural interneurons cross the midline to excite contralateral extensors and inhibit contralateral flexors to maintain balance.',
    'After-discharge: Due to reverberating circuits and multi-interneuronal pathways of varying lengths, the motor neurons continue to fire even after the stimulus is withdrawn.',
    'Response: The stimulated limb is flexed and withdrawn from the source of pain, while the opposite limb extends to support the body.',
  ],
  'Crossed Extensor Reflex (Phillipson’s Reflex)': [
    'Stimulus: A strong noxious or painful stimulus is applied to a limb (e.g., stepping on a sharp object).',
    'Receptor Activation: Nociceptors in the skin, muscle, or joints are activated.',
    'Afferent Pathway: Sensory impulses travel via flexor reflex afferents (FRA), which include small myelinated Group III (A$\\delta$) and unmyelinated Group IV (C) fibers, to the spinal cord.',
    'Integration/Mechanism: * The afferent fibers enter the spinal cord and diverge to several pools of interneurons.',
    'While one pathway initiates the ipsilateral flexor reflex (withdrawal of the stimulated limb), a branch of commissural interneurons crosses the midline to the opposite side of the spinal cord.',
    'These interneurons excite the alpha ($\\alpha$) motor neurons supplying the extensor muscles of the opposite limb.',
    'Simultaneously, they inhibit the $\\alpha$ motor neurons supplying the flexor muscles of the opposite limb (reciprocal inhibition).',
    'Latency and Duration: The response typically begins 0.2 to 0.5 seconds after the initial stimulus and exhibits a prolonged after-discharge due to reverberating interneuronal circuits.',
    'Response: The contralateral limb extends powerfully.',
    'Purpose: It supports the body weight and pushes the body away from the source of pain while the other limb is being withdrawn.',
  ],
  'Supporting Reactions (Positive and Negative)': [
    'Stimulus: Pressure is applied to the footpad (typically observed in spinal or decerebrate preparations).',
    'Receptor Activation: Tactile receptors (exteroceptors) in the footpad and proprioceptive receptors in the limb are stimulated.',
    'Afferent Pathway: Sensory signals are conveyed via tactile and proprioceptive afferents to the spinal cord.',
    'Integration: The impulses traverse a complex interneuronal circuit similar to those of the flexor/extensor reflexes.',
    'Response: There is a coordinated contraction of both flexors and extensors, which stiffens the limb into a "rigid pillar".',
    'Purpose: This stiffening allows the limbs to support the weight of the body against the pull of gravity.',
    'Stimulus: Removal of the pressure/support or a sustained stretch of the extensor muscles.',
    'Mechanism: This is an active spinal phenomenon.',
    'Response: Active relaxation of the extensor muscles.',
    'Purpose: This allows the animal to disengage the static standing position to facilitate movement.',
  ],
  'Magnet Reaction (Magnet Reflex)': [
    'Stimulus: Pressure is applied to the sole of the foot and then the examining finger is slowly withdrawn.',
    'Integration: The locus of pressure on the footpad determines the direction of extension.',
    'Response: The limb extends following the examining finger (acting as if it is drawn by a magnet).',
    'Purpose: It helps the animal maintain a stable position and prevents it from falling to one side by directing the extension toward the point of contact.',
  ],
  'Stumble Reflex': [
    'Stimulus: The top of the foot encounters an obstruction during the forward thrust of a stepping movement.',
    'Integration: Integrated entirely within the spinal cord.',
    'Stepwise Mechanism:',
    'The forward thrust of the limb is stopped temporarily.',
    'In a rapid sequence, the spinal circuitry triggers the limb to be lifted higher.',
    'The limb then proceeds forward to be placed over the obstruction.',
    'Purpose: It acts as an automatic walking controller, ensuring that a stumble does not interrupt the overall gait.',
  ],
  'Mass Reflex': [
    'Stimulus: A strong pain stimulus to the skin or excessive distension of a viscus, such as an overfilled bladder or gut.',
    'Integration: Activation of massive reverberating circuits that cause widespread discharge throughout large portions or the entire spinal cord.',
    'Coordinated Responses:',
    'Flexor Spasm: A major portion of the body\'s skeletal muscles goes into a strong flexor spasm.',
    'Visceral Evacuation: Both the bladder and colon are likely to evacuate.',
    'Cardiovascular Surge: Arterial blood pressure rises sharply, often exceeding 200 mmHg systolic.',
    'Sudomotor Activity: Large areas of the body break out into profuse sweating.',
    'Purpose: It represents a massive, non-specific discharge of spinal motor and autonomic systems when higher inhibitory control is absent. **Plantar Reflex and Babinski Reflex** The plantar reflex is a superficial reflex tested by stroking the sole of the foot; in pathological states, it presents as the Babinski sign.',
    'Normal Plantar Reflex:',
    'Stimulus: Firmly stroking the lateral aspect of the sole of the foot.',
    'Mechanism: The corticospinal tract normally provides descending excitation to the flexor motor neurons and inhibition to the extensor motor neurons of the digits.',
    'Response: Plantar flexion of the big toe and other toes.',
    'Babinski Reflex (Pathological Response):',
    'Condition: This occurs in Upper Motor Neuron (UMN) lesions (such as stroke or spinal cord injury) or during the recovery phase of spinal shock.',
    'Mechanism: Interruption of the corticospinal tract disrupts the normal inhibitory control over lumbosacral motor neurons.',
    'Response: Dorsiflexion of the big toe accompanied by fanning (abduction) of the other toes.',
    'Clinical Significance: In the recovery stage of spinal injury, this response often integrates into a wider flexor withdrawal reflex, involving flexion of the hip and knee.',
  ],
  'Clasp-Knife Reflex (Lengthening Reaction)': [
    'Step 1 (High Resistance): When a clinician attempts to passively stretch a spastic muscle (e.g., flexing the elbow of a patient with extensor spasticity), they initially encounter great resistance.',
    'Step 2 (Spindle Activation): This resistance is due to hyperactive stretch reflexes caused by increased gamma ($\\gamma$) motor neuron discharge, which sensitizes the muscle spindles.',
    'Step 3 (GTO Stimulation): As the passive flexion/stretch continues and the force becomes extreme, the Golgi Tendon Organs (GTO) are powerfully stimulated.',
    'Step 4 (Inhibitory Relay): Sensory impulses are conducted via Group Ib afferent fibers to the spinal cord, where they terminate on inhibitory interneurons.',
    'Step 5 (Autogenic Inhibition): These interneurons inhibit the alpha ($\\alpha$) motor neurons supplying the same (agonist) muscle.',
    'Response: The muscle suddenly relaxes (autogenic inhibition), and the resistance to movement disappears instantly, similar to a clasp-knife closing.',
  ],
  'Scratch Reflex': [
    'Stimulus: A mild surface stimulus, such as an insect crawling on the skin, which generates the sensation of itch.',
    'Receptor: Sensitive, rapidly adapting mechanoreceptive free nerve endings or specific itch receptors (unmyelinated C fibers).',
    'Afferent Pathway: Information is conveyed via very small, slow-conducting Type C fibers to the spinal cord.',
    'Integration: The signals activate complex, rhythmic neural circuits within the spinal cord.',
    'Mechanism: Itch (pruritus) is primarily mediated by histamine, serotonin, and specific pruritogens acting on nociceptive C-fibres (via receptors such as TRPV1 and MrgprA3). These signals are transmitted in the spinal cord via the spinothalamic tract to the somatosensory cortex. Substance P is a pain neurotransmitter and is not the primary mediator of itch.',
    'Response: A repetitive, rhythmic scratching movement of the limb is initiated, directed precisely toward the location of the irritant to remove it.',
  ],
  'Cord Righting Reflexes': [
    'Condition: Observed in "spinal animals" (e.g., an animal with a well-healed transected thoracic cord).',
    'Stimulus: Laying the animal on its side, which tilts the body relative to gravity and applies pressure to one side of the body.',
    'Mechanism: Sensory inputs from otolith organs (if the animal is tilted) or exteroceptors (due to side-of-body pressure) activate spinal interneuronal circuits.',
    'Response: The animal makes series of uncoordinated, rhythmic movements of the limbs and trunk.',
    'Net Effect: The animal attempts to raise itself from the lying position toward a standing position.',
    'Complexity: These reflexes are sophisticated enough that some spinal animals can not only right themselves but also perform inept walking movements using the hind limbs. **I. Baroreceptor Reflex (Baroreflex / Sino-aortic Reflex)** This reflex is the primary mechanism for the **short-term regulation of blood pressure**, responding within seconds to correct deviations from the normal set point.',
    'Stimulus: An increase in arterial blood pressure causes distension (stretch) of the walls of the large systemic arteries.',
    'Receptor Activation: High-pressure baroreceptors (stretch-sensitive mechanoreceptors) located in the carotid sinus and the aortic arch are stimulated.',
    'Afferent Pathway: Sensory impulses are transmitted to the brainstem via two routes:',
    'From the carotid sinus via the carotid sinus nerve (Hering’s nerve), a branch of the glossopharyngeal nerve (IX).',
    'From the aortic arch via the aortic nerve, a branch of the vagus nerve (X).',
    'Center: The afferent fibers terminate in the Nucleus Tractus Solitarius (NTS) in the medulla oblongata.',
    'Integration:',
    'Excitation of the NTS stimulates the cardioinhibitory center (Nucleus Ambiguus).',
    'Simultaneously, the NTS inhibits the Vasomotor Center (VMC) in the rostral ventrolateral medulla (RVLM) through inhibitory interneurons in the caudal ventrolateral medulla (CVLM).',
    'Efferent Response: This results in increased parasympathetic (vagal) discharge and decreased sympathetic discharge to the heart and blood vessels.',
    'Effector Action:',
    'Heart: Reflex bradycardia (decreased heart rate) and decreased myocardial contractility.',
    'Blood Vessels: Systemic vasodilation of arterioles and veins.',
    'Net Response: A rapid fall in blood pressure occurs back toward the normal level.',
  ],
  'Chemoreceptor Reflex': [
    'Stimulus: A fall in arterial $PO\_{2}$ (most sensitive when below 60 mmHg) or an increase in $PCO\_{2}$ and $H^{+}$.',
    'Receptor Action: In the glomus cells, low $O\_{2}$ levels cause the closure of $K^{+}$ channels.',
    'Depolarization: The resulting decrease in $K^{+}$ efflux causes cell depolarization, which opens voltage-gated $Ca^{2+}$ channels.',
    'Neurotransmitter Release: $Ca^{2+}$ influx triggers the release of neurotransmitters (likely ATP or acetylcholine) onto afferent nerve endings.',
    'Afferent Pathway: Impulses travel via the glossopharyngeal (IX) and vagus (X) nerves to the medulla.',
    'Center: Signals project to the medullary respiratory centers and the cardiovascular centers (NTS, VMC).',
    'Net Response: The primary effects are increased pulmonary ventilation, peripheral vasoconstriction, and primary bradycardia.',
    'Secondary Effects: Hypoxia-induced hyperventilation and increased catecholamine release often result in secondary tachycardia, overriding the primary cardiac slowing. The central chemoreceptors are highly sensitive to changes in **arterial $PCO\_{2}$** mediated through $H^{+}$ ions in the brain interstitial fluid.',
    'Stimulus: An increase in arterial $PCO\_{2}$.',
    'Diffusion: While $H^{+}$ ions pass poorly, molecular $CO\_{2}$ diffuses readily across the blood-brain barrier into the cerebrospinal fluid (CSF) and brain interstitial fluid.',
    'Hydration: $CO\_{2}$ reacts with water ($CO\_{2} \+ H\_{2}O \\rightarrow H\_{2}CO\_{3} \\rightarrow H^{+} \+ HCO\_{3}^{-}$) to release $H^{+}$ ions.',
    'Receptor Stimulation: These $H^{+}$ ions directly stimulate the central chemoreceptors (chemosensitive areas) on the ventral surface of the medulla.',
    'Net Response: Intense stimulation of the medullary respiratory centers leads to a massive increase in pulmonary ventilation.',
  ],
  'Bainbridge Reflex (Atrial Reflex)': [
    'Stimulus: Increased venous return (e.g., via intravenous infusion) causes an increase in atrial pressure and volume.',
    'Receptor Activation: Tachycardia-producing atrial receptors (TPAR) or low-pressure stretch receptors at the venoatrial junctions are stimulated.',
    'Afferent Pathway: Sensory signals are transmitted via the vagus nerve (X) to the medulla.',
    'Center: Integration occurs within the medullary cardiovascular control centers.',
    'Efferent Pathway: Efferent signals are sent back via both vagal and sympathetic nerves.',
    'Net Response: A significant increase in heart rate (tachycardia) and increased strength of heart contraction.',
  ],
  'Cushing’s Reflex / CNS Ischemic Response': [
    'Stimulus (General CNS Ischemic Response): Severe systemic hypotension (typically BP below 60 mmHg) leads to cerebral ischemia.',
    'Stimulus (Cushing\'s Reflex): A rise in intracranial pressure (ICP) to levels exceeding the arterial pressure compresses cerebral blood vessels and cuts off brain blood supply.',
    'Metabolic Trigger: Ischemia causes a rapid buildup of $CO\_{2}$ and acidic metabolites (like lactic acid) within the medullary vasomotor center.',
    'Direct VMC Excitation: These substances act as potent local stimulants, causing extreme excitation of the vasomotor center neurons.',
    'Efferent Response: A massive sympathetic discharge is initiated throughout the body.',
    'Net Response: An intense rise in systemic arterial pressure occurs, sometimes reaching as high as 250 mmHg, which attempts to overcome the ICP and restore cerebral perfusion.',
    'Secondary Response (Reflex Bradycardia): The high systemic blood pressure activates the carotid sinus baroreceptors, triggering a baroreflex that results in reflex bradycardia.',
  ],
  'Bezold–Jarisch Reflex (Coronary Chemoreflex)': [
    'Stimulus: Injection of chemicals (e.g., capsaicin, veratridine, or serotonin) into the coronary arteries, or the release of chemical substances from infarcted tissue in acute myocardial infarction (AMI).',
    'Receptor Activation: Ventricular chemoreceptors (C-fiber endings) located in the coronary arteries and ventricles are stimulated.',
    'Afferent Pathway: Information is conveyed to the brain via vagal afferent fibers.',
    'Integration: The impulses are processed in the medullary cardiovascular and respiratory centers.',
    'Net Response: A characteristic triad of apnea (initial cessation of breathing), bradycardia, and hypotension. After the initial apnea, rapid shallow breathing may follow.',
    'Clinical Significance: This reflex explains the sudden hypotension and bradycardia sometimes observed in patients with pulmonary embolism or infarcted heart tissue. **I. Pulmonary Chemoreflex** This is a non-physiological reflex often triggered during clinical events like pulmonary embolism.',
    'Stimulus: The injection of chemical substances such as capsaicin, veratridine, or serotonin into the pulmonary arteries.',
    'Receptor Activation: These chemicals stimulate specific chemoreceptors (C-fiber endings) located within the pulmonary vasculature.',
    'Afferent Pathway: Information is conveyed to the medullary centers via vagal afferent fibers.',
    'Integration: The impulses are processed in the medullary cardiovascular and respiratory centers.',
    'Response: The reflex produces a characteristic triad of apnea (or rapid shallow breathing), bradycardia, and hypotension.',
    'Clinical Correlation: This reflex is activated during a pulmonary embolism, as the resulting pulmonary microinfarction releases similar chemical mediators that trigger the response.',
  ],
  'Ventricular and Atrial Stretch Reflexes': [
    'Stimulus: Increased distension of the ventricles due to excess filling, typically caused by volume overload.',
    'Integration: Signals are processed in the medullary centers to counter the rise in pressure.',
    'Response: The reflex results in bradycardia, vasodilation, and hypotension.',
    'Purpose: It functions as a check mechanism to limit the rise in blood pressure and helps maintain basal vagal tone. The atria contain two types of stretch receptors with distinct triggers:',
    'Type A Receptors: Stimulated during atrial systole.',
    'Type B Receptors: Stimulated during peak atrial filling. **Mechanism for Type B (Volume) Reflex:**',
    'Stimulus: Increased venous return (due to fluid retention or increased blood volume) increases atrial filling.',
    'Receptor Activation: The Type B atrial stretch receptors are stimulated.',
    'Integration: The signals lead to sympathetic inhibition.',
    'Primary Response: The result is vasodilation and a decrease in blood pressure, accompanied by tachycardia.',
    'Secondary Hormonal Response: Increased atrial stretch also stimulates the release of Atrial Natriuretic Peptide (ANP), which promotes diuresis and natriuresis to reduce blood volume.',
    'Inverse Mechanism: Conversely, decreased ECF volume reduces atrial stretch, which increases ADH release from the hypothalamus to cause water retention and restore volume.',
  ],
  'Somatosympathetic, Muscle-Heart, and Exercise Pressor Reflexes': [
    'Stimulus: Stimulation of somatic afferent nerves, typically via pain (nociceptors) or proprioceptive pathways.',
    'Afferent Pathway: Impulses travel through ascending sensory pathways in the spinal cord.',
    'Integration: Collateral fibers from these pathways terminate in the medullary vasomotor center (VMC).',
    'Efferent Response: The VMC initiates an increased sympathetic outflow.',
    'Response: The result is systemic vasoconstriction and a significant increase in blood pressure.',
    'Trigger: Reflexes originating from exercising muscles and joints at the very beginning of physical activity.',
    'Response: It causes instantaneous tachycardia (increased heart rate) as soon as exercise commences.',
    'Significance: It is one of the neural mechanisms that ensure the heart rate rises before metabolic changes (like CO2 buildup) have occurred.',
    'Stimulus: Mechanical distortion of the muscle (contraction, stretch, or pressure) and the buildup of metabolites (Potassium, lactic acid, ATP).',
    'Receptors: Mechanoreceptors (responding to physical changes) and metaboreceptors (responding to chemical changes).',
    'Afferent Pathway: Signals are sent via Group III (A$\\delta$) and Group IV (C) fibers.',
    'Integration: Requires an intact brainstem; neurons in the NTS, RVLM, and CVLM process the signals.',
    'Efferent Pathway: Results in cardiac vagal inhibition and sympathetic activation.',
    'Response: Increased heart rate, blood pressure, and vascular resistance, along with a decrease in venous capacitance to boost venous return.',
  ],
  'Vasovagal and Vagal Reflexes': [
    'Trigger: Intense emotional disturbances or disturbing thoughts initiated in the cerebral cortex.',
    'Central Pathway: Signals travel from the cortex to the vasodilatory center in the anterior hypothalamus and then to the medullary vagal centers.',
    'Mechanism:',
    'The muscle vasodilator system is activated via sympathetic cholinergic fibers.',
    'The vagal cardioinhibitory center is simultaneously activated.',
    'Response: Marked bradycardia and a rapid, profound fall in blood pressure.',
    'Outcome: Reduced blood flow to the brain leads to transient loss of consciousness (fainting).',
    'Stimulus: Stimulation of the vagus nerve (cranial nerve X).',
    'Transmitter: Acetylcholine is released at the vagal nerve endings in the heart.',
    'Action:',
    'Negative Chronotropy: Decreases the rate of the SA node rhythm.',
    'Negative Dromotropy: Decreases the excitability of AV junctional fibers, slowing conduction into the ventricles.',
    'Response: Pumping rate is slowed; strong stimulation can temporarily stop the heart, leading to ventricular escape at a rhythm of 15–40 beats/minute.',
  ],
  'Ureterorenal Reflex': [
    'Stimulus: Blockage or irritation of the ureter (e.g., by a kidney stone).',
    'Integration: Initiates a sympathetic reflex.',
    'Efferent Response: Sympathetic signals are sent to the renal vasculature.',
    'Response: Constriction of the renal arterioles occurs.',
    'Outcome: There is a significant decrease in urine output from the affected kidney, which helps prevent the buildup of excessive pressure behind the obstruction. **I. Hering–Breuer Inflation Reflex** This is a protective reflex that prevents over-distension of the lungs.',
    'Stimulus: Steady increase in lung volume (inflation) during inspiration.',
    'Receptor Activation: Slowly adapting stretch receptors (pulmonary stretch receptors) located within the smooth muscle of conducting airways are stimulated.',
    'Afferent Pathway: Sensory impulses are transmitted via myelinated fibers in the vagus nerve (X) to the brainstem.',
    'Integration/Center: Impulses reach the Nucleus Tractus Solitarius (NTS) in the medulla and act on the "inspiratory off-switch".',
    'Reflex Action: The medullary inspiratory neurons are inhibited, abruptly terminating the inspiratory ramp signal.',
    'Net Response: Inspiration is stopped and the duration of expiration is increased, thereby increasing respiratory frequency while limiting tidal volume. * *Note: In adults, this reflex typically does not operate during normal breathing (eupnea) and is only activated when tidal volume exceeds \~1.5 L (three times normal).*',
  ],
  'Hering–Breuer Deflation Reflex': [
    'Stimulus: Marked deflation of the lungs.',
    'Receptor Activation: Slowly adapting stretch receptors (SARs) in the lung parenchyma and airways detect the fall in lung volume.',
    'Afferent Pathway: Information is conveyed via the vagus nerve to the medullary centers.',
    'Reflex Action: The inhibitory signals to the inspiratory center are removed and inspiratory drive is actively promoted.',
    'Net Response: There is a decrease in the duration of expiration and a stimulation of inspiration to restore lung volume.',
  ],
  'Head’s Paradoxical Reflex': [
    'Receptor: Rapidly adapting receptors (RARs), also known as pulmonary irritant receptors, located within the airways.',
    'Centre/Nucleus: The medullary respiratory centers, specifically the Dorsal Respiratory Group (DRG) located in the Nucleus Tractus Solitarius (NTS).',
    'Stimulus: Inflation of the lungs, particularly a rapid stretch.',
    'Afferent Pathway: Sensory impulses are carried from the receptors in the lungs to the brainstem via the vagus nerve (CN X).',
    'Step 1: The stimulus (lung inflation) activates the rapidly adapting receptors.',
    'Step 2: Signals are sent via the vagus nerve to the NTS/DRG in the medulla.',
    'Step 3: Unlike the standard Hering–Breuer inflation reflex (which inhibits inspiration), this reflex triggers a paradoxical further inflation or an additional, gasping inspiratory effort.',
    'Purpose: This reflex is responsible for the production of deep sighs, which help to re-expand collapsed areas of the lungs.',
    'Clinical Significance: It is clinically significant for the initial inflation of the lungs in a newborn baby, providing the powerful inspiratory force required to expand the previously collapsed alveoli for the first time.',
  ],
  'J-Receptor Reflex (Juxtacapillary Reflex / Apnea Reflex)': [
    'Stimulus: Pulmonary capillary engorgement (e.g., congestive heart failure), pulmonary edema, or the presence of chemical irritants such as capsaicin.',
    'Receptor Activation: J receptors (sensory nerve endings) located in the alveolar walls in close proximity (juxtaposition) to the pulmonary capillaries are stimulated.',
    'Afferent Pathway: Sensory signals are transmitted via unmyelinated C-fiber endings in the vagus nerve to the medulla.',
    'Integration: The impulses reach the medullary respiratory and cardiovascular centers.',
    'Reflex Response (J-Reflex):',
    'Respiratory: Sudden apnea (cessation of breathing) followed by rapid shallow breathing and bronchoconstriction.',
    'Cardiovascular: Bradycardia and marked hypotension.',
    'Somatic: Skeletal muscle tone is abruptly reduced.',
    'Clinical Significance: Excitation of these receptors is believed to be a major cause of the sensation of dyspnea (shortness of breath) in patients with heart failure or pulmonary congestion.',
  ],
  'Cough Reflex': [
    'Stimulus: Pulmonary irritant receptors (naked nerve endings) in the epithelium of the trachea, bronchi, and bronchioles are stimulated by mechanical or chemical irritants.',
    'Afferent Pathway: Sensory impulses are transmitted to the brainstem. While the tracheal response is largely mediated by the vagus nerve (X), irritation in other areas may involve different pathways.',
    'Center: The signals are integrated in the medullary respiratory centers.',
    'The Act of Coughing:',
    'Step 1: A deep inspiration occurs, drawing a large volume of air into the lungs.',
    'Step 2: The glottis closes tightly and the vocal cords are firmly approximated to entrap the air.',
    'Step 3: The abdominal muscles and internal intercostal muscles contract forcefully, causing the intrapleural pressure to rise sharply to 100 mm Hg or more.',
    'Step 4: The glottis and vocal cords open instantaneously, allowing the high-pressure air to explode outward at velocities as high as 600 miles per hour.',
    'Result: The rapid, high-pressure air flow carries with it any foreign matter or irritants present in the respiratory passages.',
  ],
  'Sneeze Reflex': [
    'Stimulus: Irritation or presence of dust in the nasal passages or nasopharynx.',
    'Afferent Pathway: Impulses travel via the trigeminal nerve (V) to the medulla. This irritation can be triggered by odors, chemicals (like chlorine or ammonia), or mechanical irritants.',
    'Mechanism: The mechanical events are nearly identical to those of the cough reflex, with one major exception regarding the glottis: * A deep inspiration is taken. * A forceful expiratory effort is initiated.',
    'Glottis Action: Unlike the cough reflex, where the glottis closes to build pressure, the glottis remains continuously open throughout the sneeze reflex.',
    'Soft Palate Action: The uvula is depressed, which directs a large portion of the rapidly expelled air through the nose as well as the mouth \[This is a standard physiological description; the sources note the mechanism is "almost same as coughing" apart from the open glottis, 361\].',
    'Result: The blast of air clears the nasal passages of the irritating material.',
  ],
  'Hiccup Reflex': [
    'Stimulus: While the exact physiological trigger is often unknown, they can be associated with gastric distension or visceral irritation.',
    'Mechanism:',
    'Step 1: There is a spasmodic contraction of the inspiratory muscles, particularly the diaphragm.',
    'Step 2: This results in a sudden, instantaneous inspiration.',
    'Step 3: During this rapid inhalation, the glottis closes abruptly.',
    'Result: The sudden closure of the glottis while air is being rapidly drawn in produces the typical sound associated with a hiccup.',
    'Clinical Note: Firmly holding one\'s breath can often stop the reflex by increasing $PCO\_{2}$, which suppresses the spasmodic drive.',
  ],
  'Respiratory Inhibition during Swallowing (Deglutition Apnea)': [
    'Stimulus: The process is initiated voluntarily when the tongue pushes a bolus of food into the back of the mouth, where it touches swallowing receptors around the pharyngeal opening (specifically on the tonsillar pillars).',
    'Afferent Pathway: Sensory impulses are transmitted from these receptors to the brainstem via the trigeminal (V) and glossopharyngeal (IX) nerves, and to a lesser extent the vagus nerve (X).',
    'Center: Signals reach the deglutition (swallowing) center located in the Nucleus Tractus Solitarius (NTS) and Nucleus Ambiguus in the medulla and lower pons.',
    'Mechanism of Inhibition: The swallowing center sends specific inhibitory signals to the medullary respiratory center.',
    'Reflex Response: Respiration is abruptly halted at any point in its cycle for a fraction of a second to several seconds (usually less than 6 seconds).',
    'Protective Coordination: Simultaneously, the glottis closes, the vocal cords are approximated, and the soft palate is pulled upward to seal off the respiratory passages.',
    'Result: This ensures a clear passage for the bolus into the esophagus while preventing "choking" or aspiration pneumonia.',
  ],
  'Respiratory Inhibition during Vomiting': [
    'Stimulus: The vomiting center in the medulla is stimulated by various inputs, such as overdistension or irritation of the duodenum and stomach, or chemical triggers in the Area Postrema (CTZ).',
    'Afferent Pathway: Sensory signals are primarily conveyed via vagal and sympathetic afferent fibers.',
    'Stepwise Mechanism of the Act:',
    'Phase 1 (Initial Inspiration): The act begins with a deep breath (preliminary inspiration).',
    'Phase 2 (Glottis Action): The glottis closes tightly and the vocal cords move centrally to seal the trachea.',
    'Phase 3 (Palatal Action): The soft palate is lifted to close the posterior nares, preventing vomitus from entering the nasal cavity.',
    'Phase 4 (Pressure Build-up): The diaphragm contracts strongly downward and the abdominal wall muscles contract simultaneously, building high intragastric pressure.',
    'Respiratory Inhibition: Throughout the forceful expulsion phase, the respiratory center is inhibited by the vomiting center to ensure that the chyme is forced upward through the esophagus rather than into the lungs.',
    'Result: The "vomiting reflex" safely rids the upper GI tract of irritants while providing maximal protection to the airway.',
  ],
  'Peristaltic Reflex (Myenteric Reflex / Law of the Gut)': [
    'Stimulus: The primary stimulus is distension of the gut wall, which occurs when a bolus of food or chyme enters a segment of the intestine. Other stimuli can include chemical or physical irritation of the mucosal lining.',
    'Receptor Activation: Mechanoreceptors (stretch receptors) in the mucosa and muscularis mucosa detect the distension and initiate the reflex via the myenteric (Auerbach\'s) plexus.',
    'Integration: Sensory impulses are transmitted to the myenteric (Auerbach’s) plexus located between the circular and longitudinal muscle layers.',
    'Propulsive Segment (Orad to the bolus):',
    'In the segment behind the bolus, local excitatory cholinergic neurons are activated, releasing acetylcholine and substance P.',
    'This causes the circular muscles to contract and the longitudinal muscles to relax, forming a contractile ring that narrows the lumen.',
    'Receiving Segment (Anal to the bolus):',
    'In the segment ahead of the bolus, inhibitory neurons are activated, releasing vasoactive intestinal peptide (VIP) and nitric oxide (NO).',
    'This leads to receptive relaxation of the circular muscles and contraction of the longitudinal muscles, widening the lumen to receive the bolus.',
    'Response (The Law of the Gut): The contractile ring moves progressively toward the anus, propelling the intestinal contents forward into the relaxed receiving segment.',
  ],
  'Enterogastric Reflex': [
    'Stimulus: The reflex is triggered by the presence of chyme in the duodenum, specifically sensing factors such as distension, high acidity (pH below 3.5–4), hyperosmolality, or the presence of protein breakdown products and fats.',
    'Receptor Activation: Sensory nerve endings in the duodenal wall monitor these conditions.',
    'Afferent Pathway: Information is transmitted via three potential routes: directly through the ENS, through extrinsic sympathetic fibers via prevertebral ganglia, or via the vagus nerve to the brainstem.',
    'Integration: Signals are integrated to provide inhibitory feedback to the stomach.',
    'Response:',
    'The reflex inhibits the "pyloric pump" (vigorous antral peristaltic contractions).',
    'Simultaneously, it increases the tone of the pyloric sphincter to resist the passage of chyme.',
    'Net Effect: Gastric emptying is slowed, and gastric acid secretion is inhibited, ensuring the duodenum is not overloaded beyond its digestive capacity.',
  ],
  'Gastrocolic Reflex': [
    'Stimulus: Distension of the stomach by the accumulation of food following ingestion.',
    'Primary Mediator: This reflex is primarily neural, mediated by the extrinsic autonomic nervous system (long vagal and sympathetic reflexes) and the enteric nervous system (ENS). Hormones such as gastrin and cholecystokinin (CCK) released in response to gastric distension play a secondary, modulatory role but are not the primary drivers.',
    'Reflex Action: Neural and hormonal signals travel from the stomach to the colon.',
    'Response: There is a marked increase in colonic motility, specifically triggering mass movements in the proximal and distal colon.',
    'Result: Fecal material is propelled into the rectum, distending the rectal wall and initiating the desire for defecation.',
  ],
  'Gastroileal Reflex': [
    'Stimulus: Stretching of the stomach wall by food (gastric distension).',
    'Afferent Pathway/Integration: The reflex is believed to be mediated by the vagus nerve (a long reflex) and potentially augmented by the hormone gastrin.',
    'Reflex Action: Signals are transmitted to the terminal part of the ileum.',
    'Response:',
    'The motility of the terminal ileum is significantly enhanced.',
    'The ileocecal sphincter (valve) relaxes, which normally remains tonically closed to prevent backflow from the colon.',
    'Result: The contents of the ileum are rapidly emptied into the cecum or ascending colon through the open ileocecal valve.',
  ],
  'Intestino-intestinal Reflex': [
    'Stimulus: Over-distension or extreme irritation of a specific segment of the small intestine,.',
    'Receptor Activation: Stretch receptors within the gut wall of the affected segment are activated.',
    'Afferent Pathway and Integration: Sensory signals are transmitted through the local enteric nervous system and via vagovagal pathways to the brainstem,.',
    'Reflex Action: The central or local integration results in the transmission of inhibitory signals to the remainder of the intestinal tract,.',
    'Response: The rest of the intestine relaxes, effectively halting motor activity to prevent further movement of chyme into the already distended or injured area,.',
    'Clinical Significance: This reflex, along with the peritoneointestinal reflex, can contribute to intestinal paralysis in pathological states like peritonitis,.',
  ],
  'Colonocolonic Reflex': [
    'Stimulus: Distension of one part or segment of the colon,.',
    'Afferent Pathway: Impulses are carried from the distended segment to the prevertebral sympathetic ganglia,.',
    'Integration: The reflex is integrated within the sympathetic ganglia and the enteric nervous system.',
    'Efferent Response: Inhibitory sympathetic signals are transmitted back to the entire colon.',
    'Response: The entire colon relaxes in response to the localized distension,.',
    'Purpose: It helps manage the volume and transit of fecal material by allowing the colon to accommodate incoming contents through widespread relaxation.',
  ],
  'Colonoileal Reflex': [
    'Stimulus: Distension of the colon or cecum, or the presence of an irritant (such as an inflamed appendix) in the cecal region,.',
    'Afferent Pathway: Sensory signals are conducted from the colon and cecum to the prevertebral sympathetic ganglia,.',
    'Integration: Integration occurs within the sympathetic ganglia, which then relay inhibitory commands back to the terminal part of the small intestine.',
    'Response:',
    'Inhibition of ileal peristalsis: The propulsive movements of the terminal ileum are significantly weakened or stopped.',
    'Contraction of the ileocecal sphincter: The tone of the ileocecal valve (sphincter) is intensified, causing it to close more tightly,.',
    'Net Effect: The emptying of ileal contents into the colon is delayed or blocked, which prevents the entry of additional chyme until the colon has processed its current contents,.',
  ],
  'Duodenocolic Reflex': [
    'Stimulus: Distension of the duodenum occurs when chyme is emptied into it from the stomach.',
    'Afferent Pathway: Sensory signals are initiated in the duodenal wall and transmitted through the extrinsic autonomic nervous system.',
    'Integration: The reflex is mediated centrally and likely involves transmission through prevertebral sympathetic ganglia back to the colon.',
    'Response: The reflex facilitates or initiates mass movements in the colon. These are modified peristaltic contractions that propel fecal material en masse toward the rectum.',
    'Purpose: It ensures that the lower gut prepares to accommodate new material by evacuating its contents.',
  ],
  'Peritoneointestinal Reflex': [
    'Stimulus: Irritation of the peritoneum, typically caused by infection, inflammation, or injury.',
    'Afferent Pathway: Pain and irritation signals are sent to the central nervous system via extrinsic nerves.',
    'Mechanism of Inhibition: The reflex triggers an increased discharge of non-adrenergic (sympathetic) fibers in the splanchnic nerves.',
    'Reflex Action: These sympathetic signals strongly inhibit the excitatory enteric nerves (myenteric and submucosal plexuses) within the gut wall.',
    'Response: The result is a profound inhibition or complete paralysis of intestinal motility.',
    'Clinical Significance: This reflex is a primary cause of adynamic (paralytic) ileus, characterized by a "silent abdomen" and abdominal distension.',
  ],
  'Renointestinal Reflex': [
    'Stimulus: Irritation or inflammation of the kidney, such as that caused by renal calculi (stones) or urinary tract infections.',
    'Afferent Pathway: Sensory impulses from the irritated renal tissue travel via autonomic nerves to the integrating centers.',
    'Mechanism: The stimulus activates an inhibitory autonomic circuit directed toward the gastrointestinal tract.',
    'Response: The reflex results in the inhibition of intestinal motor activity.',
    'Outcome: Like the peritoneointestinal reflex, the renointestinal reflex can contribute to the development of intestinal stasis or adynamic ileus in patients suffering from renal colic.',
  ],
  'Deglutition Reflex (Swallowing Reflex)': [
    'Stimulus: A bolus of food is prepared in the mouth.',
    'Mechanism: The tongue "voluntarily" squeezes or rolls the bolus posteriorly against the hard palate.',
    'Action: This movement forces the food bolus into the pharynx, where it touches epithelial swallowing receptors. This phase represents the core of the **deglutition reflex**, pushing the bolus into the esophagus while protecting the respiratory passage.',
    'Receptors: Tactile receptor areas around the pharyngeal opening, especially on the tonsillar pillars.',
    'Afferent Pathway: Sensory impulses travel via the trigeminal (V), glossopharyngeal (IX), and vagus (X) nerves to the brainstem.',
    'Center: The swallowing center (deglutition center), located in the Nucleus Tractus Solitarius (NTS) and Nucleus Ambiguus in the medulla and lower pons.',
    'Efferent Pathway: Motor signals return to the pharynx and upper esophagus through the 5th, 7th, 9th, 10th, and 12th cranial nerves.',
    'Reflex Events:',
    'Nasal Protection: The soft palate is pulled upward to close the posterior nares, preventing food from entering the nasal cavities.',
    'Passage Creation: The palatopharyngeal folds move medially to form a narrow sagittal slit for the bolus.',
    'Airway Protection: The vocal cords approximate tightly, the larynx moves forward and upward, and the epiglottis swings back to cover the laryngeal opening, preventing food entry into the trachea.',
    'Esophageal Entry: The upper esophageal sphincter (UES) relaxes, allowing the bolus to enter the esophagus.',
    'Propulsion: The pharyngeal muscular wall contracts (superior to inferior), propelling the bolus into the esophagus via a fast peristaltic wave.',
    'Respiratory Inhibition: The swallowing center inhibits the medullary respiratory center, causing deglutition apnea (temporary cessation of breathing).',
    'Primary Peristalsis: A continuation of the pharyngeal peristaltic wave spreads down the esophagus to the stomach in about 8–10 seconds.',
    'Sphincter Action: As the wave approaches the stomach, the lower esophageal sphincter (LES) relaxes (mediated by VIP and nitric oxide) to allow the food to enter.',
  ],
  'Esophago-esophageal Contractile Reflex (Secondary Peristalsis)': [
    'Stimulus: Distension of the esophagus caused by a retained food bolus or an experimental balloon.',
    'Receptor Activation: Mechanoreceptors in the esophageal wall are stimulated by the local stretch.',
    'Pathway Integration:',
    'Intrinsic: Mediated by the local myenteric nervous system circuits.',
    'Extrinsic: Signals are transmitted via vagal afferent fibers to the medullary swallowing center.',
    'Efferent Response: Motor impulses return to the esophagus through the glossopharyngeal (IX) and vagus (X) nerves.',
    'Response: A secondary peristaltic wave (contractile ring) is initiated just above the bolus, which continues until the esophagus is cleared.',
  ],
  'Vesicointestinal Reflex': [
    'Stimulus: Irritation or excessive distension of the urinary bladder.',
    'Afferent Pathway: Sensory impulses (pain or stretch) are conveyed from the bladder wall to the spinal cord via the pelvic nerves.',
    'Integration: The reflex is integrated within the autonomic centers of the spinal cord.',
    'Efferent Response: The reflex triggers an increased discharge of sympathetic fibers (potentially via splanchnic nerves).',
    'Mechanism of Action: These sympathetic signals strongly inhibit the excitatory enteric nerves (myenteric and submucosal plexuses) within the intestinal wall.',
    'Response: The reflex results in the inhibition of intestinal motor activity, which can lead to intestinal paralysis (adynamic ileus) in severe cases. **I. Chewing Reflex (Mastication Reflex)** While chewing is largely a voluntary activity, the rhythmic act itself is primarily a reflex phenomenon coordinated by brainstem nuclei and the motor branch of the **trigeminal (V) nerve**.',
    'Stimulus: The presence of a bolus of food in the mouth.',
    'Reflex Inhibition: The pressure of the bolus against the oral lining causes reflex inhibition of the muscles of mastication.',
    'Jaw Drop: This inhibition allows the lower jaw to drop.',
    'Stretch Reflex Activation: The sudden dropping of the jaw initiates a stretch reflex in the jaw-closing muscles (e.g., masseter and temporalis).',
    'Rebound Contraction: The stretch reflex leads to a rebound contraction, which automatically raises the jaw to close the teeth.',
    'Compression Cycle: Raising the jaw compresses the food bolus again against the oral lining, which re-initiates the reflex inhibition.',
    'Repetition: This cycle repeats continuously to facilitate the grinding and mixing of food.',
  ],
  'Vomiting Reflex': [
    'Stimulus: Overdistension or irritation of the duodenum provides the strongest stimulus, though inputs also arrive from the pharynx, stomach, and esophagus.',
    'Afferent Transmission: Nerve impulses are transmitted via vagal and sympathetic afferent fibers to the brainstem vomiting center.',
    'Antiperistalsis (Prelude): Before the actual vomiting act, antiperistalsis (reverse peristalsis) begins, moving backward up the intestine from as far down as the ileum to push contents into the duodenum and stomach.',
    'Airway and Throat Preparation:',
    'A deep breath is taken.',
    'The hyoid bone and larynx are raised to pull the upper esophageal sphincter (UES) open.',
    'The glottis closes and vocal cords move together to protect the lungs.',
    'The soft palate is lifted to close the posterior nares.',
    'Pressure Build-up: The diaphragm contracts downward and the abdominal wall muscles contract simultaneously, building high intragastric pressure by squeezing the stomach.',
    'Esophageal Entry: The lower esophageal sphincter (LES) relaxes, allowing the high pressure to force gastric contents upward into the esophagus.',
    'Expulsion: Continued strong contractions and sharp rises in intra-abdominal pressure cause the UES to relax, allowing the chyme to explode through the pharynx and into the mouth for external expulsion.',
  ],
  'Gastric Relaxations (Receptive, Adaptive, and Feedback)': [
    'Trigger: The act of chewing and swallowing food.',
    'Afferent Pathway: Information is transmitted through vagal afferents from the pharynx and esophagus.',
    'Integration: A vagovagal reflex occurs in the medulla.',
    'Efferent Mechanism: Vagal efferents release inhibitory neurotransmitters, specifically vasoactive intestinal peptide (VIP) and nitric oxide (NO), at the nerve endings.',
    'Response: The fundus and body of the stomach relax, allowing the organ to bulge outward to accommodate food. This reflex is a response to the physical presence of food within the stomach.',
    'Trigger: Gastric distension (stretching of the stomach wall) as food accumulates.',
    'Mechanism: Like receptive relaxation, it is mediated primarily by a vagovagal reflex.',
    'Response: The stomach wall relaxes further to allow for a greater volume of food (up to 0.8–1.5 L) without a significant rise in pressure. This reflex acts as a braking mechanism to regulate the flow of chyme into the small intestine.',
    'Trigger: The entry of acidic chyme, fatty acids, or hypertonic solutions into the duodenum.',
    'Reflex Pathways:',
    'Neural: Activation of the enterogastric reflex, which sends inhibitory signals to the stomach via the enteric nervous system and extrinsic sympathetic nerves.',
    'Hormonal: Release of CCK, GIP, and secretin from the duodenal mucosa.',
    'Response: General inhibition of gastric motility and relaxation of the stomach wall to slow gastric emptying.',
  ],
  'Vagovagal Reflexes': [
    'Stimulus: Distension of the gut wall (such as the stomach or duodenum) by food or the presence of specific chemical products of digestion.',
    'Receptor Activation: Mechanoreceptors (stretch receptors) or chemoreceptors in the gastrointestinal mucosa and muscularis are activated.',
    'Afferent Pathway: Sensory signals are transmitted to the brainstem via vagal afferent fibers, which constitute approximately 80% of all fibers in the vagus nerves.',
    'Integrating Center: The impulses reach the medulla oblongata, specifically the Nucleus Tractus Solitarius (NTS) and the dorsal motor nucleus of the vagus.',
    'Efferent Response: The medulla sends reflex signals back to the gastrointestinal tract via vagal efferent fibers.',
    'Effector Action:',
    'For Gastric Relaxation (Adaptive/Receptive): Vagal efferents release inhibitory neurotransmitters, primarily Vasoactive Intestinal Peptide (VIP) and Nitric Oxide (NO), causing the smooth muscle in the stomach wall to relax to accommodate food.',
    'For Secretion: Vagal efferents release Acetylcholine (cholinergic) to stimulate parietal cells and Gastrin-Releasing Peptide (GRP) (non-cholinergic) to stimulate G cells, increasing the production of digestive juices.',
    'Net Result: The stomach bulges outward to store food (up to 1.5 L) without a significant rise in pressure, and the GI tract prepares for digestion.',
  ],
  'Salivatory Reflexes / Taste-Salivary Reflex': [
    'Stimulus: Contact of food with the mouth cavity, especially taste stimuli (sour tastes are most potent) or tactile stimuli (such as smooth objects like a pebble).',
    'Receptor: Taste buds on the tongue, pharynx, or palate, and tactile receptors in the oral mucosa.',
    'Afferent Pathway:',
    'Anterior 2/3 of tongue: Signals travel via the lingual nerve, then the chorda tympani (branch of the facial nerve, VII).',
    'Posterior 1/3 of tongue: Signals travel via the glossopharyngeal nerve (IX).',
    'Pharynx/Epiglottis: Signals travel via the vagus nerve (X).',
    'Integrating Center: All taste afferents synapse in the Nucleus Tractus Solitarius (NTS) in the medulla, which then projects to the superior and inferior salivatory nuclei.',
    'Efferent Pathway:',
    'Parotid Gland: Inferior salivary nucleus → IX nerve → otic ganglion → auriculotemporal nerve.',
    'Submandibular/Sublingual Glands: Superior salivary nucleus → VII nerve → chorda tympani → submandibular ganglion.',
    'Effector Action: Postganglionic cholinergic fibers release Acetylcholine, VIP, and bradykinin, which stimulate glandular tissue and cause significant vasodilation to provide nutrients for secretion.',
    'Net Result: Copious, enzyme-rich, and watery saliva is secreted to facilitate chewing, swallowing, and digestion.',
  ],
  'Feeding Reflexes': [
    'Stimulus: Recognition of food (sight, smell, or taste) and the internal state of hunger.',
    'Integrating Centers: The mammillary bodies and the amygdala are key structures for controlling the patterns of these reflexes.',
    'Integration with Appetite: The lateral hypothalamus (feeding center) initiates the drive to eat, while the ventromedial hypothalamus (satiety center) eventually opposes it when the animal is full.',
    'Stepwise Mechanism of Specific Acts:',
    'Licking: Coordinated by the mammillary bodies in response to pleasant gustatory or olfactory cues.',
    'Chewing (Mastication Reflex): The presence of a bolus of food in the mouth causes reflex inhibition of the muscles of mastication, letting the jaw drop; this triggers a stretch reflex that causes a rebound contraction, closing the teeth and compressing the bolus again to repeat the cycle.',
    'Swallowing (Deglutition Reflex): Initiated voluntarily when the tongue pushes food against the palate; once the food bolus touches the tonsillar pillars, involuntary pharyngeal muscle contractions occur automatically to move the food into the esophagus while sealing off the airway.',
    'Net Result: These reflexes ensure that food is effectively processed and moved into the alimentary tract for digestion.',
  ],
  'Micturition Reflex': [
    'Stimulus: As the bladder fills, the accumulation of urine causes a steady increase in the tension and stretch of the bladder wall.',
    'Receptor Activation: Once intravesical pressure rises above a critical threshold, sensory stretch receptors in the bladder wall and posterior urethra are stimulated.',
    'Afferent Pathway: Sensory signals are transmitted via afferent fibers in the pelvic nerves to the sacral segments (S2–S4) of the spinal cord.',
    'Integration Center: The reflex is integrated within the sacral micturition center of the spinal cord; it is subject to voluntary inhibition or facilitation by higher brain centers in the pons and cerebral cortex.',
    'Efferent Response: Motor signals return to the bladder through parasympathetic efferent fibers also traveling in the pelvic nerves.',
    'Mechanism of Emptying:',
    'Parasympathetic activation triggers strong contraction of the detrusor muscle.',
    'Simultaneously, the internal urethral sphincter relaxes, opening the bladder neck for urine flow.',
    'The reflex is self-regenerative: an initial contraction further activates stretch receptors, leading to a cycle of increasingly powerful contractions until the reflex reaches fatigue or the bladder is emptied.',
    'Somatic Control: Once the reflex is powerful enough, it initiates a secondary reflex via the pudendal nerves to inhibit the external urethral sphincter, allowing urination to occur if voluntary conditions are met.',
  ],
  'Defecation Reflexes': [
    'Stimulus: Fecal material enters the rectum, causing distension of the rectal wall.',
    'Afferent/Integration: Signals are initiated and spread locally through the myenteric plexus in the gut wall.',
    'Response: This triggers peristaltic waves in the descending colon, sigmoid, and rectum, forcing feces toward the anus.',
    'Mechanism: As the wave approaches the anus, inhibitory signals from the myenteric plexus cause the internal anal sphincter to relax.',
    'Stimulus: Stimulation of sensory nerve endings in the rectum by fecal filling.',
    'Afferent Pathway: Signals are transmitted via the pelvic nerves to the sacral segments of the spinal cord.',
    'Reflex Relay: The spinal cord sends back intensified commands through parasympathetic fibers in the pelvic nerves.',
    'Response: These signals powerfully intensify peristaltic waves and relax the internal anal sphincter.',
    'Expulsion: If the person voluntarily relaxes the external anal sphincter (via the pudendal nerve) and contracts their abdominal muscles, the feces are forced out of the anal canal.',
  ],
  'Milk Ejection Reflex (Milk Let-down Reflex)': [
    'Stimulus: The suckling of the infant on the mother\'s nipple.',
    'Receptor: Tactile receptors located in and around the nipple are activated.',
    'Afferent Pathway: Sensory impulses travel via somatic nerves to the spinal cord and ascend through the spinothalamic tract to the hypothalamus.',
    'Center: The ascending signals activate the paraventricular nucleus (PVN) and supraoptic nucleus (SON) of the hypothalamus (diencephalon). These nuclei are not in the midbrain — they are hypothalamic nuclei that project axons down to the posterior pituitary.',
    'Efferent Limb (Humoral): Stimulated hypothalamic neurons trigger the release of oxytocin from nerve terminals in the posterior pituitary gland into the bloodstream.',
    'Effector Action: Blood carries oxytocin to the breasts, where it binds to receptors on myoepithelial cells that form a lattice surrounding the milk-laden alveoli.',
    'Response: The myoepithelial cells contract, squeezing milk from the alveoli into the lactiferous ducts at a pressure of 10–20 mmHg, allowing it to flow to the nipple for the baby.',
  ],
  'Parturition Reflex': [
    'Stimulus: Toward term, the fetal head presses on and stretches the uterine cervix.',
    'Receptor: Stretch receptors in the cervix detect this mechanical distortion.',
    'Afferent Pathway: Increased sensory impulses are transmitted through an ascending pathway to the hypothalamus.',
    'Efferent Response (Humoral): The hypothalamus stimulates the posterior pituitary to increase the secretion of oxytocin.',
    'Mechanism of Action: Oxytocin increases the excitability of the myometrium (uterine muscle) and stimulates the production of prostaglandins, which are also potent uterine stimulants.',
    'Response: The uterus contracts vigorously, pushing the fetus further downward into the birth canal.',
    'Positive Feedback Loop: This downward movement further increases the stretch of the cervix, which triggers even more oxytocin release and stronger contractions.',
    'Completion: This vicious cycle continues, aided by reflex abdominal muscle contractions, until the baby is expelled from the birth canal.',
  ],
  'Coitus Reflex / Sexual Reflexes': [
    'Erection:',
    'Trigger: Tactile stimulation of the glans penis or psychic arousal.',
    'Pathway: Parasympathetic signals from the sacral cord travel via the nervi erigentes (pelvic nerves).',
    'Mechanism: These nerves release Nitric Oxide (NO) and VIP; NO stimulates the formation of cGMP, which relaxes the penile arteries and the smooth muscle of cavernous sinusoids.',
    'Result: Rapid blood engorgement compresses the veins, trapping blood in the erectile tissue and making the penis turgid.',
    'Emission:',
    'Trigger: Intensity of sexual stimulation reaches a peak.',
    'Pathway: Sympathetic impulses (T12 to L2) leave the cord via the hypogastric nerves.',
    'Mechanism: Contraction of the vas deferens, prostate, and seminal vesicles expels sperms and glandular fluids into the internal urethra to form semen.',
    'Ejaculation:',
    'Trigger: Filling of the internal urethra initiates signals via the pudendal nerves to the sacral spinal cord.',
    'Mechanism: Spinal centers (L5, S1–S3) trigger rhythmic contractions of the bulbocavernosus and ischiocavernosus muscles.',
    'Result: Semen is propelled out of the urethra to the exterior; this entire process constitutes the male orgasm.',
    'Erection and Engorgement: Parasympathetic signals (nervi erigentes) from the sacral plexus dilate the arteries of the erectile tissue around the introitus and clitoris, causing them to become engorged and sensitive.',
    'Lubrication: Parasympathetic signals stimulate the Bartholin glands and the vaginal epithelium to secrete mucus, ensuring satisfactory lubrication for coitus.',
    'Orgasm: Reaching peak stimulation initiates a reflex that causes rhythmic contractions of the perineal muscles and potentially enhances uterine motility to facilitate sperm transport.',
  ],
  'Ejaculation Reflex': [
    'Trigger: Sexual stimulation reaches a peak intensity.',
    'Integration: Reflex centers in the spinal cord initiate sympathetic impulses that leave the cord at T-12 to L-2.',
    'Pathway: These impulses travel through the hypogastric and pelvic sympathetic nerve plexuses to reach the internal genital organs.',
    'Step 1 (Vas Deferens): Contraction of the smooth muscles of the vas deferens and its ampulla forces sperms forward into the internal urethra.',
    'Step 2 (Accessory Glands): Simultaneous contractions of the muscular coats of the prostate gland and seminal vesicles expel their respective fluids into the internal urethra.',
    'Step 3 (Semen Formation): These fluids mix with mucus already secreted by the bulbourethral glands to form semen.',
    'Step 4 (Internal Sphincter): The internal urethral sphincter constricts to prevent semen from entering the bladder (retrograde ejaculation).',
    'Trigger: The sudden filling of the internal urethra with semen provides a feeling of "fullness".',
    'Afferent Pathway: Sensory signals are transmitted via the pudendal nerves to the sacral segments of the spinal cord (L5, S1–S3).',
    'Neurotransmitter: Carbon monoxide (CO) has been proposed as a transmitter in this neural circuit (G.K. Pal).',
    'Efferent Response: The spinal centers send rhythmic motor commands back through the pudendal nerve.',
    'Effector Action: These signals trigger powerful, rhythmic contractions of the ischiocavernosus and bulbocavernosus muscles (skeletal muscles) at the base of the penis.',
    'Step 5 (Expulsion): Rhythmic wave-like increases in pressure within the urethra and erectile tissue propel the semen to the exterior.',
    'Step 6 (Orgasm): This entire process, often accompanied by rhythmic contractions of pelvic and trunk muscles, constitutes the male orgasm.',
  ],
  'Axon Reflex / Flare Response': [
    'Stimulus: A firm stroke or noxious stimulus is applied to the skin (e.g., using a pointed object).',
    'Receptor Activation: Local cutaneous sensory endings are stimulated.',
    'Orthodromic Conduction: Sensory impulses are generated and travel orthodromically (normally) toward the spinal cord via the primary sensory afferent fiber.',
    'Impulse Relaying: At a branch point in the same sensory neuron, the impulse is also relayed antidromically (in the opposite direction) down collateral branches.',
    'Effector Branching: These collateral branches terminate directly on the walls of local arterioles.',
    'Chemical Release: The sensory endings on the blood vessels release potent vasodilators, specifically Substance P and Calcitonin Gene-Related Peptide (CGRP).',
    'Response: These chemicals produce marked arteriolar dilation.',
    'Net Effect: Redness spreads outward from the site of the initial injury to the surrounding area, manifesting as the flare.',
  ],
  'Sudomotor Reflex (Axon Reflex in Sweating)': [
    'Stimulus: Local skin stimulation, such as heat or the intradermal injection of Acetylcholine (ACh).',
    'Afferent Activation: The stimulus activates receptors on a terminal of a cutaneous sensory axon.',
    'Conduction and Relay: Similar to the flare response, the impulse travels toward a branch point and is then relayed antidromically along another branch of the same neuron.',
    'Effector Action: This secondary branch terminates near the eccrine sweat glands.',
    'Secretion: The release of ACh from these terminals (or the activation of sympathetic cholinergic fibers) stimulates the glandular tissue to produce sweat.',
    'Net Result: Localized sweating occurs in the region surrounding the point of stimulation.',
  ],
  'Local Skin Temperature Reflexes': [
    'Stimulus: Local exposure to extreme heat (e.g., a hot lamp) or extreme cold (e.g., cold water).',
    'Receptor Activation: Thermoreceptors (cold or warmth receptors) in the skin are stimulated.',
    'Afferent Pathway: Sensory signals are conducted from the skin receptors to the dorsal horn of the spinal cord.',
    'Integration: The impulses are processed within segmental cord centers, though the intensity of the response is modulated by descending signals from the hypothalamic thermostat.',
    'Efferent Limb: Signals return to the same skin area via autonomic nerve fibers.',
    'Response to Heat:',
    'Induces local vasodilation through sympathetic inhibition and direct thermal effects.',
    'Promotes local sweating to increase evaporative heat loss.',
    'Response to Cold:',
    'Triggers local vasoconstriction through sympathetic activation to conserve heat.',
    'Causes cessation of local sweating.',
    'Net Purpose: These reflexes help prevent excessive heat exchange in localized portions of the body and are proportional to the body\'s overall thermal needs.',
  ],
  'Pupillary Light Reflex (Direct and Consensual)': [
    'Stimulus: Bright light is focused on the retina of one eye.',
    'Receptor Activation: The retinal ganglion cells (specifically photoreceptors like rods and cones) are stimulated.',
    'Afferent Pathway: Sensory impulses travel via the optic nerve (CN II) to the optic tract.',
    'Integration Center (Midbrain): A few fibers from the optic tract bypass the lateral geniculate body and project to the pretectal nucleus in the midbrain.',
    'Bilateral Relay: From the pretectal nucleus, secondary neurons project bilaterally to both the ipsilateral and contralateral Edinger-Westphal nuclei (the visceral motor nuclei of the oculomotor nerve).',
    'Efferent Pathway (Parasympathetic):',
    'Preganglionic parasympathetic fibers travel via the oculomotor nerve (CN III) to the ciliary ganglion located behind the eyeball.',
    'Postganglionic fibers travel via the short ciliary nerves to the eyeball.',
    'Effector Action: These fibers stimulate the sphincter pupillae muscles of the iris.',
    'Net Response:',
    'Direct Light Reflex: The pupil of the eye receiving the light constricts.',
    'Consensual Light Reflex: The pupil of the opposite eye also constricts simultaneously due to the bilateral projection from the pretectal nucleus to both Edinger-Westphal nuclei.',
  ],
  'Accommodation Reflex': [
    'Stimulus: Shifting the gaze from a distant object to a near object (within 6 meters).',
    'Afferent Pathway: Visual signals travel from the retinal ganglion cells to the lateral geniculate body (LGB) and then to the primary visual cortex (Area 17\) in the occipital lobe.',
    'Center/Integration: Signals are processed in the visual cortex and then transmitted via the occipitomesencephalic pathway to the Edinger-Westphal nucleus in the midbrain.',
    'Efferent Pathway: Motor impulses return to the eye via the oculomotor nerve (CN III).',
    'Triple Reflex Response (Near Response):',
    'Lens Accommodation: The ciliary muscle contracts, which relaxes the suspensory ligaments (zonules). This allows the elastic lens to bulge and become more convex, increasing its refractive power for near vision.',
    'Pupillary Constriction (Miosis): The sphincter pupillae contracts, narrowing the pupil to increase the depth of focus and decrease spherical aberrations.',
    'Convergence: The medial rectus muscles of both eyes contract, causing the eyeballs to rotate medially so that the image falls on the corresponding points of both retinas.',
  ],
  'Tympanic Reflex (Acoustic / Attenuation Reflex)': [
    'Stimulus: Exposure to a prolonged, loud sound (typically below 1000 Hz).',
    'Latency: The reflex occurs after a latent period of approximately 40 to 160 milliseconds.',
    'Afferent Signal: Loud sound vibrations are transmitted from the cochlea through the central nervous system auditory pathways.',
    'Efferent Response: Motor signals are sent to the two tiny muscles of the middle ear.',
    'Effector Action:',
    'Stapedius Muscle: Innervated by CN VII, it attaches to the neck of the stapes and contracts to pull the footplate of the stapes outward, away from the oval window.',
    'Tensor Tympani Muscle: Innervated by CN V3, it attaches to the handle of the malleus and contracts to pull the malleus medially, increasing the tension and rigidity of the tympanic membrane.',
    'Net Response: These actions together increase the overall rigidity of the ossicular system, which greatly reduces the conduction of low-frequency sound vibrations (by 30 to 40 dB) to the cochlea.',
    'Purpose: It protects the delicate hair cells of the cochlea from damage and helps mask low-frequency background noise, allowing a person to concentrate on human speech frequencies.',
  ],
  'Vestibulo-ocular Reflex (VOR / Doll’s Eyes Reflex)': [
    'Stimulus: Head rotation or angular acceleration.',
    'Receptor Activation: Hair cells in the semicircular ducts (within the vestibular apparatus) are stimulated by the inertia-driven movement of endolymph.',
    'Afferent Pathway: Sensory impulses travel via the vestibular nerve (CN VIII) to the brainstem.',
    'Center/Integration: Impulses reach the vestibular nuclei (specifically the superior and medial nuclei).',
    'Inter-nuclear Relay: From the vestibular nuclei, signals are transmitted through the medial longitudinal fasciculus (MLF) to the nuclei of the cranial nerves that control eye movement: CN III (Oculomotor), CN IV (Trochlear), and CN VI (Abducens).',
    'Efferent Pathway: Motor signals travel via these cranial nerves to the extraocular muscles.',
    'Net Response: The eyes rotate in a direction equal and opposite to the rotation of the head.',
    'Clinical Correlation (Doll\'s Eyes): In a healthy individual, turning the head causes the eyes to move in the opposite direction to maintain fixation (positive Doll\'s Eyes). The absence of this movement is a diagnostic marker used in evaluating brainstem function and brain death.',
  ],
  'Vestibulocollic Reflex': [
    'Stimulus: Tilting or rotation of the head, which changes the orientation of the head relative to gravity or initiates angular acceleration.',
    'Receptor Activation: Sensory hair cells in the otolith organs (detecting linear acceleration/tilt) and the semicircular canals (detecting rotation) are stimulated.',
    'Afferent Pathway: Sensory impulses are transmitted via the vestibular (8th) cranial nerve to the brainstem.',
    'Integrating Center: The impulses terminate in the vestibular nuclei (specifically the medial and inferior nuclei).',
    'Efferent Response: Motor commands are sent from the vestibular nuclei to the cervical segments of the spinal cord via vestibulospinal pathways.',
    'Effector Action: These signals trigger the contraction of specific head and neck muscles.',
    'Net Response: The reflex provides stability of the head position during movement, resisting displacement to maintain an upright or steady orientation.',
  ],
  'Labyrinthine Righting Reflex': [
    'Stimulus: Tilting of the body or head, which alters the orientation of the vestibular apparatus relative to the pull of gravity.',
    'Receptor Activation: Otolith organs (maculae of the utricle and saccule) detect the change in gravitational pull.',
    'Afferent Pathway: Information is conveyed to the brain via the vestibular nerve.',
    'Integrating Center: The reflex is integrated within the midbrain.',
    'Response: The midbrain sends motor signals to the neck muscles.',
    'Effector Action: Contraction of neck muscles occurs to oppose the tilt.',
    'Net Result: The head is kept level (upright) despite the body being tipped from side to side.',
  ],
  'Neck Righting Reflex': [
    'Pre-condition: This reflex typically occurs after the head has already been righted by other mechanisms (like the labyrinthine reflex), while the body remains tilted.',
    'Stimulus: Stretching of the neck muscles caused by the rotational discrepancy between the upright head and the tilted trunk.',
    'Receptor Activation: Muscle spindles in the neck muscles detect the sustained stretch.',
    'Integrating Center: Integrated in the midbrain.',
    'Stepwise Response: The reflex triggers a sequential righting of the body parts:',
    'Phase 1: Righting of the shoulders.',
    'Phase 2: Righting of the thorax.',
    'Phase 3: Righting of the pelvis.',
    'Net Result: The entire body is restored to an upright position in alignment with the head.',
  ],
  'Body-on-Head Righting Reflex': [
    'Stimulus: Pressure on the side of the body, such as when an animal or human is laid on its side on a firm surface.',
    'Receptor Activation: Exteroceptors (tactile receptors) in the skin on the side of the body receiving the pressure are stimulated.',
    'Afferent Pathway: Sensory signals regarding the asymmetric pressure are sent to the brain.',
    'Integrating Center: Integrated in the midbrain.',
    'Response: The midbrain initiates motor commands to the neck muscles.',
    'Effector Action: Contraction of neck muscles occurs to lift the head.',
    'Net Result: Righting of the head occurs so that it assumes an upright position relative to the ground.',
  ],
  'Body-on-Body Righting Reflex': [
    'Stimulus: Asymmetric pressure is applied to the side of the body, such as when a person is laid on their side on a firm surface.',
    'Receptor Activation: Exteroceptors (tactile receptors) in the skin on the side of the body receiving the pressure are stimulated.',
    'Center/Integration: Sensory information is transmitted to the midbrain, where the reflex is integrated.',
    'Response: The midbrain initiates motor commands to the trunk and limb muscles.',
    'Effect: The body is righted toward an upright position, even if the head is prevented from righting itself sideways.',
  ],
  'Limb Righting Reflex': [
    'Stimulus: A sustained stretch of the limb muscles occurs due to a change in body position.',
    'Receptor Activation: Muscle spindles within the stretched limb muscles are activated.',
    'Center/Integration: Information is conveyed to the midbrain, specifically involving the red nucleus.',
    'Response: Motor signals are sent from the midbrain to the skeletal muscles of the body.',
    'Effect: A coordinated righting movement of the body is produced to restore it to its normal orientation.',
  ],
  'Optical Righting Reflex': [
    'Stimulus: Visual cues regarding the orientation of the environment or the body’s position in space are detected.',
    'Receptor Activation: Visual receptors (photoreceptors) in the retina are stimulated by the visual environment.',
    'Afferent Pathway: Visual information is transmitted via the visual pathways to the brain.',
    'Center/Integration: Unlike most other righting reflexes integrated in the midbrain, the center for this reflex is the visual cortex.',
    'Response: The cortex processes the visual data and sends motor commands to the neck muscles.',
    'Effect: Righting of the head occurs, ensuring it stays upright and the eyes remain fixed on visual targets despite bodily movement.',
  ],
  'Tonic Neck Reflex': [
    'Stimulus: A change in head position in relation to the body occurs (e.g., tilting or turning the head).',
    'Receptor Activation: Proprioceptors (such as muscle spindles) in the upper part of the neck are stimulated by the movement.',
    'Integrating Pathway: Sensory signals reach the medulla and are processed via the reticulospinal and tectospinal pathways.',
    'Efferent Response: The brainstem sends motor commands to the limbs that produce sustained muscle contractions.',
    'Response Variations: The specific pattern of muscle tone change depends on the direction of head movement:',
    'Ventroflexion (Head tilted down): The upper limbs flex while the hind limbs extend.',
    'Turning to one side: The limb on the side toward which the head is turned (the jaw limb) extends, while the opposite limb (the occipital limb) flexes.',
    'Extension (Head tilted back): The forelimbs extend and the hind limbs flex.',
    'Purpose: These adjustments help the individual maintain stability and posture in the specific position assumed (e.g., looking down at the ground or looking up into a tree).',
  ],
  'Tonic Labyrinthine Reflex': [
    'Stimulus: A change in the body’s position in space, which alters the orientation of the head relative to the pull of gravity.',
    'Receptor Activation: The otolith organs (utricle and saccule) of the vestibular apparatus are stimulated by the constant pull of gravity.',
    'Afferent Pathway: Signals regarding the head\'s orientation are transmitted via the vestibular nerve to the brainstem.',
    'Integration: The reflex is integrated within the medulla, primarily involving the vestibular nuclei.',
    'Efferent Response: Motor commands are sent to the limb muscles via the vestibulospinal tracts.',
    'Stepwise Response Patterns:',
    'Supine Position (on the back): Extensor rigidity is maximum, causing all four limbs to be maximally extended.',
    'Prone Position (on the belly): Extensor rigidity is minimum.',
    'Lateral Position: Rigidity decreases as the animal is turned toward either side.',
    'Purpose: It helps an animal maintain muscle tone and stability in an erect posture.',
  ],
  'Grasp Reflex': [
    'Stimulus: An object, such as a stick, is brought into contact with or in close proximity to the animal’s limbs.',
    'Integration: The sensory input (tactile and proprioceptive) is processed in the midbrain.',
    'Response Mechanism:',
    'Step 1: The limb muscles respond by grasping the object.',
    'Step 2: Simultaneously, the limbs are extended.',
    'Purpose: It is considered a primitive reflex that assists the animal in standing up and supporting its posture.',
  ],
  'Placing Reactions': [
    'Stimulus: Rapid linear acceleration of the body, such as when a blindfolded animal is suddenly brought down from a height.',
    'Receptor Activation: Vestibular receptors in the inner ear detect the downward acceleration.',
    'Reflex Pathway: Signals are processed in the midbrain and transmitted via the vestibulospinal tract.',
    'Response: The forelimbs extend and the toes spread widely.',
    'Purpose: This reaction prepares the animal to land steadily and safely on the ground.',
    'Condition: This reflex is integrated in the motor cortex and is severely impaired in decorticate preparations.',
    'Stimulus: The subject is pushed laterally while standing.',
    'Mechanism: Following the initial hopping reaction (see below), the subject places its feet firmly on the ground.',
    'Result: The animal or human attains and maintains a new stable position despite the displacement.',
  ],
  'Hopping Reaction': [
    'Stimulus: A normal animal or human being is pushed laterally (to the side) while standing.',
    'Integration: The reflex is integrated within the motor cortex.',
    'Stepwise Mechanism:',
    'Step 1: The body is displaced from its stable center of gravity.',
    'Step 2: The subject reflexively takes a series of short steps (hops) in the direction of the push.',
    'Step 3: These hops continue until the subject\'s base of support is realigned with its center of gravity.',
    'Outcome: The body maintains its postural balance and prevents a fall.',
    'Clinical Note: Like the cortical placing reaction, this response is grossly impaired following decortication, indicating its dependence on an intact motor cortex.',
  ],
  'Corneal Reflex': [
    'Stimulus: Mechanical touch or irritation to the cornea (e.g., by a wisp of cotton).',
    'Receptor: Sensory nerve endings (nociceptors and mechanoreceptors) in the corneal epithelium are activated.',
    'Afferent Pathway: Sensory impulses are transmitted to the brainstem via the trigeminal nerve (CN V).',
    'Integrating Center: The reflex is processed and integrated in the pons and medulla.',
    'Efferent Pathway: Motor signals return to the eye via the facial nerve (CN VII).',
    'Response: The orbicularis oculi muscle contracts, resulting in immediate blinking or closure of the eyelid.',
  ],
  'Gag Reflex (Pharyngeal Reflex)': [
    'Stimulus: Tactile stimulation or irritation of the posterior pharyngeal wall or the tonsillar pillars.',
    'Receptor: Sensitive tactile receptors in the pharyngeal mucosa detect the mechanical stimulus.',
    'Afferent Pathway: Sensory signals are carried to the brainstem through the glossopharyngeal (IX) and vagus (X) nerves.',
    'Integrating Center: The signals are integrated in the medullary swallowing/gag centers (specifically the Nucleus Tractus Solitarius and Nucleus Ambiguus).',
    'Efferent Pathway: Motor commands are relayed back to the pharynx through the glossopharyngeal (IX) and vagus (X) nerves.',
    'Response: A sudden, forceful contraction of the pharyngeal muscles (gagging) occurs.',
  ],
  'Jaw Reflex': [
    'Stimulus: Tapping on the jaw or chin or the presence of a bolus of food in the mouth.',
    'Mechanism (Chewing Cycle):',
    'Reflex Inhibition: Pressure from the food bolus against the oral lining causes reflex inhibition of the muscles of mastication, causing the jaw to drop.',
    'Stretch Activation: The sudden dropping of the jaw initiates a stretch reflex in the jaw-closing muscles (such as the masseter).',
    'Reflex Pathway: Motor impulses are primarily carried by the trigeminal nerve (CN V) to the muscles of mastication; certain clinical diagnostic markers for the jaw reflex also involve the glossopharyngeal nerve (CN IX).',
    'Response: A rebound contraction occurs, which raises the jaw to close the teeth and compress the bolus, repeating the cycle.',
  ],
  'Tracheal Reflex': [
    'Stimulus: Mechanical or chemical irritation of the tracheal epithelium (e.g., during tracheobronchial suctioning).',
    'Receptor: Pulmonary irritant receptors (naked nerve endings) in the trachea are stimulated.',
    'Afferent Pathway: Sensory impulses travel via the vagus nerve (CN X) to the medulla.',
    'Integrating Center: Integration occurs in the medullary respiratory centers.',
    'Reflex Act (Stepwise):',
    'Deep Inspiration: A large volume of air is rapidly drawn into the lungs.',
    'Entrapment: The glottis closes tightly to trap the air.',
    'Pressure Build-up: The abdominal and expiratory muscles contract forcefully, causing a sharp rise in internal pressure.',
    'Explosion: The glottis and vocal cords open instantaneously, allowing air to explode outward at high velocity.',
    'Response: The explosive blast of air carries foreign matter and irritants out of the trachea.',
  ],
};

export function getMechanism(name) {
  return MECHANISMS[name] || null;
}